Quizz 1. Forest fires

In [4]:
#import the libraries
import numpy as np
import pandas as pd
#titles for graphs
from IPython.display import display, Markdown

In [2]:
#import the csv
df = pd.read_csv("forestfires.csv")

In [14]:
def title(text):
    display(Markdown(f'### {text}'))

#let's get basic info about the data
title('Overview')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
display(df)        # first and last 5 rows - get a feel for the data

title('Statistics')
display(df.describe())    # stats for numeric columns (mean, min, max...)

title('Info')
df.info()                 # column types + non-null counts

title('Nulls per column')
nulls = df.isnull().sum()
display(nulls[nulls > 0])               # null count per column


title('Duplicate Rows')
display(df.duplicated().sum())          # number of duplicate rows
display(df[df.duplicated(keep=False)]) # show duplicate rows


title('Distinct Values per Column')
display(df.nunique())                   # distinct values per column

title('Correlation Matrix')
corr_matrix = df.corr(numeric_only=True)

mask = (corr_matrix.abs() >= 0.5) & ~np.eye(len(corr_matrix), dtype=bool)
filtered = corr_matrix.where(mask).dropna(how='all').dropna(axis=1, how='all')

display(filtered.fillna(''))

### Overview

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

### Statistics

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,4.669246,4.299807,90.644681,110.872340,547.940039,9.021663,18.889168,44.288201,4.017602,0.021663,12.847292
std,2.313778,1.229900,5.520111,64.046482,248.066192,4.559477,5.806625,16.317469,1.791653,0.295959,63.655818
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.400000,0.000000,0.000000
25%,3.000000,4.000000,90.200000,68.600000,437.700000,6.500000,15.500000,33.000000,2.700000,0.000000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.300000,42.000000,4.000000,0.000000,0.520000
75%,7.000000,5.000000,92.900000,142.400000,713.900000,10.800000,22.800000,53.000000,4.900000,0.000000,6.570000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,6.400000,1090.840000

### Info

<class 'pandas.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       517 non-null    int64
 1   Y       517 non-null    int64
 2   month   517 non-null    str
 3   day     517 non-null    str
 4   FFMC    517 non-null    float64
 5   DMC     517 non-null    float64
 6   DC      517 non-null    float64
 7   ISI     517 non-null    float64
 8   temp    517 non-null    float64
 9   RH      517 non-null    int64
 10  wind    517 non-null    float64
 11  rain    517 non-null    float64
 12  area    517 non-null    float64
dtypes: float64(8), int64(3), str(2)
memory usage: 52.6 KB

### Nulls per column

Series([], dtype: int64)

### Duplicate Rows

np.int64(4)

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
52   4  3   aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0   0.00
53   4  3   aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   0.0   0.00
99   3  4   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   0.0   0.00
100  3  4   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   0.0   0.00
214  4  4   mar  sat  91.7   35.8   80.8   7.8  17.0  27   4.9   0.0  28.66
215  4  4   mar  sat  91.7   35.8   80.8   7.8  17.0  27   4.9   0.0  28.66
302  3  6   jun  fri  91.1   94.1  232.1   7.1  19.2  38   4.5   0.0   0.00
303  3  6   jun  fri  91.1   94.1  232.1   7.1  19.2  38   4.5   0.0   0.00

### Distinct Values per Column

X          9
Y          7
month     12
day        7
FFMC     106
DMC      215
DC       219
ISI      119
temp     192
RH        75
wind      21
rain       7
area     251
dtype: int64

### Correlation Matrix

,X,Y,FFMC,DMC,DC,ISI,temp,RH
X,,0.539548,,,,,,
Y,0.539548,,,,,,,
FFMC,,,,,,0.531805,,
DMC,,,,,0.682192,,,
DC,,,,0.682192,,,,
ISI,,,0.531805,,,,,
temp,,,,,,,,-0.52739
RH,,,,,,,-0.52739,

Q3. Target is burned surface which is column "area".
There's 12 predictive variables and 1 target.

# Done with Quizz 1